version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api/APIDockerfile
    container_name: properties_api
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - Seq__ServerUrl=http://localhost:5341
    depends_on:
      - seq

  ui:
    build:
      context: .
      dockerfile: ui/UIDockerfile
    container_name: properties_ui
    ports:
      - "3000:80"
    depends_on:
      - api

  seq:
    image: datalust/seq
    container_name: seq
    ports:
      - "5341:5341"
      - "80:80"
    environment:
      - ACCEPT_EULA=Y
    restart: always